### ISSUE TITLE
FarmHarvestObjectEvent missing

### ISSUE THREAD

**Issue by bCamba** [ift-gftc/opentraceability#52]
Farm Harvest events can be either Transformation or Object events as per the image below:

![image](https://github.com/user-attachments/assets/4f427ac5-c840-4602-89da-633ad80f5127)

However they are implemented as transform events only in the library. We were in need of having it as object event as well, so I implemented a version that worked for us, similar to what you had for the Feed Mill events which can also be either object or transform events. I will open a PR to fix that together with the issue.

**Comment by Get-Rect** [comment]
Hi @bCamba. Thank you for pointing this out. I've merged a PR with your recommended fix here, https://github.com/ift-gftc/opentraceability/pull/55.

The main difference is I did not rename the FarmHarvestEvent type to FarmHarvestTransformationEvent to prevent errors in projects consuming the package when they update to the latest version.

**Comment by Get-Rect** [comment]
Hi @bCamba. Thank you for pointing this out. I've merged a PR with your recommended fix here, https://github.com/ift-gftc/opentraceability/pull/55.

The main difference is I did not rename the FarmHarvestEvent type to FarmHarvestTransformationEvent to prevent errors in projects consuming the package when they update to the latest version.
